const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
const out=process.env.UI_SCREENSHOTS||'/tmp/exploration-shots';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu']});const page=await browser.newPage({viewport:{width:600,height:960},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());await page.goto(require('node:url').pathToFileURL(path.join(__dirname,'../index.html')).href);
await page.evaluate(async()=>{AssetPreloader.ready=true;await Game.startNew(true);GameState.trainerName='Explorer';await Game.confirmStarter(STARTERS[0]);MiniGameSession.seen=new Set(Object.keys(MiniGameSession.guides));});await page.waitForTimeout(600);
async function shot(name){await page.waitForTimeout(350);await page.screenshot({path:out+'/'+name+'.png'});assert.deepEqual(errors,[]);}
await shot('map-portrait');const dock=await page.locator('#nav-choices').boundingBox();assert.ok(dock.y>650);assert.ok(dock.y+dock.height<=961);
// All gym schedules have at most two stops, avoid the gym, and don't change the ten normal steps.
await page.evaluate(()=>{for(const region of ['kanto','johto'])for(let gym=0;gym<8;gym++){GameState.region=region;GameState.bossesDefeated=gym;delete GameState.exploration;const s=Exploration.state();if(s.events.length<1||s.events.length>2||s.events.some(e=>e.at>=10))throw Error('Bad schedule');}GameState.region='kanto';GameState.bossesDefeated=3;});
const event=async(kind)=>{await page.evaluate(kind=>{GameState.exploration={key:'kanto:3',carrying:false,events:[{id:0,kind,at:0,status:'pending'}]};Exploration.maybe();},kind);await shot(kind);};
await event('bush');await page.getByRole('button',{name:'Cut',exact:true}).click();assert.equal(await page.evaluate(()=>Exploration.current.status),'resolved');const gold=await page.evaluate(()=>GameState.gold);await page.evaluate(()=>Exploration.resolve(Exploration.current,'ability',GameState.party[0]));assert.equal(await page.evaluate(()=>GameState.gold),gold);await shot('bush-cleared');
// Resolved event resumes after an actual page reload with no repeated reward.
await page.reload();await page.evaluate(async()=>{AssetPreloader.ready=true;await Game.continueGame();});await page.waitForTimeout(500);assert.equal(await page.locator('#screen-field.active').count(),1);assert.equal(await page.evaluate(()=>GameState.gold),gold);await page.getByRole('button',{name:'Continue',exact:true}).click();await page.waitForTimeout(300);assert.equal(await page.locator('#screen-map.active').count(),1);
await event('machine');assert.equal(await page.getByRole('button',{name:'Power up',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Turn the crank',exact:true}).click();assert.equal(await page.evaluate(()=>Exploration.current.reward.gold),6);
// Electric and fire abilities, including secondary types and fainted exclusions.
await page.evaluate(()=>{GameState.party.push(makePokemon(25,5,'assets/sprites/25.png','Pikachu','electric'),makePokemon(4,5,'assets/sprites/4.png','Charmander','fire'));});await event('light');await page.getByRole('button',{name:'Power up',exact:true}).click();assert.equal(await page.evaluate(()=>Exploration.current.actor),25);await shot('powered');
await page.evaluate(()=>{GameState.party[0].hp=10;});await event('fire');await page.getByRole('button',{name:'Warm up',exact:true}).click();assert.equal(await page.evaluate(()=>GameState.party[0].hp),25);await shot('warm-fire');
for(const kind of ['water','flying','rock','ice']){await event(kind);const info=await page.evaluate(()=>{const d=Exploration.specs[Exploration.current.kind];return {alt:d.alt};});await page.getByRole('button',{name:info.alt,exact:true}).click();assert.equal(await page.evaluate(()=>Exploration.current.status),'resolved');}
// Other ability successes and the two alternate story items.
await page.evaluate(()=>{GameState.party.push(makePokemon(7,5,'assets/sprites/7.png','Squirtle','water'),makePokemon(16,5,'assets/sprites/16.png','Pidgey','flying'),makePokemon(74,5,'assets/sprites/74.png','Geodude','rock'));});
for(const [kind,action,id]of [['water','Retrieve',7],['flying','Fly up',16],['rock','Move rocks',74]]){await event(kind);await page.getByRole('button',{name:action,exact:true}).click();assert.equal(await page.evaluate(()=>Exploration.current.actor),id);}
for(const item of ['scarf','charm']){await event(item);await page.getByRole('button',{name:'Carry it'}).click();assert.equal(await page.evaluate(()=>GameState.exploration.item),item);await page.evaluate(item=>{const e={id:1,kind:'owner',item,at:0,status:'pending'};GameState.exploration.events.push(e);Exploration.show(e);},item);await page.getByRole('button',{name:'Return '+item,exact:true}).click();assert.equal(await page.evaluate(()=>GameState.exploration.carrying),false);}
// Check actual matching environments for water, electric and fire scenes.
for(const [kind,gym]of [['water',1],['machine',2],['fire',6]]){await page.evaluate(({kind,gym})=>{GameState.bossesDefeated=gym;GameState.exploration={key:'kanto:'+gym,events:[{id:0,kind,at:0,status:'pending'}]};Exploration.maybe();},{kind,gym});await shot(kind+'-environment');}await page.evaluate(()=>GameState.bossesDefeated=3);
// Story survives branches and reload, follows after 2 completed encounters, pays once.
await page.evaluate(()=>{GameState.exploration={key:'kanto:3',carrying:false,events:[{id:0,kind:'backpack',at:0,status:'pending'},{id:1,kind:'owner',at:2,status:'pending'}]};Exploration.maybe();});await shot('backpack');await page.getByRole('button',{name:'Carry it'}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>GameState.exploration.carrying),true);
await page.evaluate(()=>{const n=GameState.map.find(n=>n.unlocked&&!n.done);MapEngine.completeNode(n.idx);MapEngine._showNav();});await page.waitForTimeout(300);assert.equal(await page.locator('#screen-field.active').count(),0);
await page.evaluate(()=>{const n=GameState.map.find(n=>n.unlocked&&!n.done&&n.row===1);MapEngine.completeNode(n.idx);MapEngine._showNav();});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>Exploration.current.kind),'owner');await shot('owner');await page.getByRole('button',{name:'Return backpack'}).click();assert.equal(await page.evaluate(()=>GameState.exploration.carrying),false);assert.equal(await page.evaluate(()=>Exploration.current.reward.gold),20);
await page.evaluate(()=>SurgeEngine.start({idx:0}));await shot('surge-intro');await page.evaluate(()=>SurgeEngine.startGame());await page.waitForTimeout(250);if(await page.locator('.minigame-guide').count())await page.locator('.minigame-guide button').click();await shot('surge-game');const portrait=await page.locator('#challenge-character-img').boundingBox();assert.ok(portrait.height>=180);
await page.setViewportSize({width:800,height:1280});await page.evaluate(()=>MapEngine._showNav());await shot('map-large');await page.setViewportSize({width:360,height:640});await event('machine');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:960,height:600});await page.evaluate(()=>MapEngine._showNav());await shot('map-landscape');
assert.deepEqual(errors,[]);await browser.close();console.log('Exploration passed: schedules, abilities, alternatives, story progression, reload and reward idempotency, portrait layout. '+out);
})().catch(e=>{console.error(e);process.exit(1)});
