const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
(async()=>{
 const b=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu']}),p=await b.newPage({viewport:{width:600,height:960},hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route(/^https?:/,r=>r.abort());await p.goto(require('node:url').pathToFileURL(path.join(__dirname,'../index.html')).href);const out='/tmp/feed-menus';fs.mkdirSync(out,{recursive:true});
 const help=async()=>{if(await p.locator('.minigame-guide button').count())await p.locator('.minigame-guide button').click();};
 const fit=async sel=>{for(const el of await p.locator(sel).all()){if(!await el.isVisible())continue;if(p.viewportSize().width<440&&sel.includes('profile-actions'))await el.scrollIntoViewIfNeeded();const r=await el.boundingBox(),v=p.viewportSize();assert(r.x>=-1&&r.y>=-1&&r.x+r.width<=v.width+1&&r.y+r.height<=v.height+1,sel+JSON.stringify(r));}};
 await p.waitForTimeout(500);await p.screenshot({path:out+'/no-profile.png'});assert.deepEqual(errors,[]);
 await p.evaluate(async()=>{AssetPreloader.ready=true;await Game.startNew(true);GameState.trainerName='Alex';await Game.confirmStarter(STARTERS[0]);const a=loadProfiles();a[0].leagueUnlocked=true;saveProfiles(a);createProfile('Sophie');createProfile('Max');});await p.waitForTimeout(650);
 for(const [w,h] of [[600,960],[800,1280],[360,640],[960,600]]){
  await p.setViewportSize({width:w,height:h});await p.evaluate(()=>{ProfileEngine._updateStartScreen();showScreen('start');});await p.waitForTimeout(500);await p.screenshot({path:out+`/menu-${w}.png`});await fit('#start-menu button, .apb-switch-btn, .apb-edit-age-btn, .menu-settings summary');
  await p.locator('.menu-settings summary').click();await p.screenshot({path:out+`/settings-${w}.png`});await p.locator('.menu-settings summary').click();
  await p.evaluate(()=>ProfileEngine.show());await p.waitForTimeout(500);await p.screenshot({path:out+`/profiles-${w}.png`});await fit('.profile-actions button, #btn-profiles-back');
 }
 await p.setViewportSize({width:600,height:960});await p.locator('.profile-age-btn').first().click();await fit('#age-change-modal button');await p.locator('#age-modal-cancel').click();await p.locator('.profile-delete-btn').last().click();assert(await p.locator('#overlay').isVisible());await p.evaluate(()=>document.getElementById('overlay').classList.add('hidden'));assert.equal(await p.evaluate(()=>loadProfiles().length),3);
 for(const tier of [1,2,3]){
  await p.evaluate(tier=>{delete GameState.snorlaxFeed;GameState.currentNodeIndex=0;SnorlaxEngine._node=GameState.map[0];MiniGameSession.seen.add('snorlax-active');GameState.skillTiers={comparison:tier};SnorlaxEngine.startGame();const s=GameState.snorlaxFeed;s.tier=tier;s.max=[0,5,15,30][tier];s.target=Math.ceil(s.max*.6);s.low=1;s.high=s.max;SnorlaxEngine.show();},tier);await help();await p.waitForTimeout(400);await p.locator('.feed-snorlax').click();assert.match(await p.locator('#feed-clue').textContent(),/hungry/);
  for(const [w,h] of [[600,960],[800,1280],[360,640],[960,600]]){await p.setViewportSize({width:w,height:h});await fit('.feed-option,.feed-submit');await p.screenshot({path:out+`/feed-${tier}-${w}.png`});}
  await p.setViewportSize({width:600,height:960});await p.emulateMedia({reducedMotion:'reduce'});
  await p.locator('.feed-option').first().click();await p.locator('.feed-submit').click();await p.evaluate(()=>SnorlaxEngine.feed(1));await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>GameState.snorlaxFeed.attempts),1);assert.equal(await p.locator('.feed-feedback').getAttribute('data-direction'),'up');
  const saved=await p.evaluate(()=>({target:GameState.snorlaxFeed.target,low:GameState.snorlaxFeed.low}));await p.reload();await p.evaluate(()=>{GameState=SaveManager.load();MiniGameSession.seen.add('snorlax-active');SaveManager.resume();});await p.waitForTimeout(450);await help();assert.deepEqual(await p.evaluate(()=>({target:GameState.snorlaxFeed.target,low:GameState.snorlaxFeed.low})),saved);
  await p.locator('.feed-option').last().click();await p.locator('.feed-submit').click();await p.waitForTimeout(350);assert.equal(await p.locator('.feed-feedback').getAttribute('data-direction'),'down');
  let limit=0;while(await p.evaluate(()=>GameState.snorlaxFeed.phase!=='won')){assert(++limit<12);await p.evaluate(()=>{const o=SnorlaxEngine.options();SnorlaxEngine.feed(o[Math.floor(o.length/2)]);});await p.waitForTimeout(350);}
  const gold=await p.evaluate(()=>GameState.gold);await p.evaluate(()=>{SnorlaxEngine.settle();SnorlaxEngine.feed(GameState.snorlaxFeed.target);});assert.equal(await p.evaluate(()=>GameState.gold),gold);await p.screenshot({path:out+`/won-${tier}.png`});await p.reload();await p.evaluate(()=>{GameState=SaveManager.load();MiniGameSession.seen.add('snorlax-active');SaveManager.resume();});await p.waitForTimeout(450);assert.equal(await p.evaluate(()=>GameState.gold),gold);await p.locator('.feed-submit').click();assert.equal(await p.evaluate(()=>!!GameState.snorlaxFeed),false);
 }
 // Real pointer swipe and reload during flight settle one serving exactly once.
 await p.emulateMedia({reducedMotion:'no-preference'});await p.evaluate(()=>{SnorlaxEngine.startGame();GameState.snorlaxFeed.target=3;GameState.snorlaxFeed.low=1;GameState.snorlaxFeed.high=5;SnorlaxEngine.show();});await help();await p.waitForTimeout(450);const r=await p.locator('.feed-option').first().boundingBox();await p.mouse.move(r.x+r.width/2,r.y+40);await p.mouse.down();await p.mouse.move(r.x+r.width/2,r.y-30,{steps:5});await p.mouse.up();assert.equal(await p.evaluate(()=>GameState.snorlaxFeed.pending),1);await p.screenshot({path:out+'/feeding.png'});await p.reload();await p.evaluate(()=>{GameState=SaveManager.load();MiniGameSession.seen.add('snorlax-active');SaveManager.resume();});await p.waitForTimeout(450);assert.equal(await p.evaluate(()=>GameState.snorlaxFeed.attempts),1);assert.equal(await p.evaluate(()=>GameState.snorlaxFeed.pending),null);
 assert.deepEqual(errors,[]);await b.close();console.log('Feed Snorlax all tiers, higher/lower, swipe, duplicate guards, pending/win reload and menu/profile tablet layouts passed.');
})().catch(e=>{console.error(e);process.exit(1)});
