const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu']}),page=await browser.newPage({viewport:{width:600,height:960},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());await page.goto(require('url').pathToFileURL(path.join(__dirname,'../index.html')).href);const out='/tmp/fossil-dig';fs.mkdirSync(out,{recursive:true});
await page.evaluate(async()=>{AssetPreloader.ready=true;await Game.startNew(true);GameState.trainerName='Dig Test';await Game.confirmStarter(STARTERS[0]);MiniGameSession.seen.add('fossil-active');});await page.waitForTimeout(600);
const help=async()=>{if(await page.locator('.minigame-guide button').count())await page.locator('.minigame-guide button').click();};
const init=async(tier=2,reward='crystal')=>{await page.evaluate(({tier,reward})=>{delete GameState.fossilDig;GameState.difficultyTier=tier;const e={id:0,kind:'fossil',at:0,status:'pending'};GameState.exploration={key:'kanto:0',events:[e],fossilScheduled:true};FossilDig.begin(e);GameState.fossilDig.reward=reward;FossilDig.save();},{tier,reward});await help();await page.waitForTimeout(450);};
// Scheduling keeps normal node graph and owner stories intact.
assert.deepEqual(await page.evaluate(()=>{const result=[];for(const bi of [0,1,2,3,4,5,6,7]){GameState.bossesDefeated=bi;const s={events:[{id:0,kind:'rock',status:'pending',at:3}]};FossilDig.schedule(s);result.push(s.events[0].kind);}GameState.bossesDefeated=0;const s={events:[{id:0,kind:'backpack',status:'pending'},{id:1,kind:'owner',status:'pending'}]};FossilDig.schedule(s);return {result,story:s.events.map(e=>e.kind)};}),{result:['fossil','rock','fossil','rock','fossil','rock','fossil','rock'],story:['backpack','owner']});
for(const tier of [1,2,3]){
 await init(tier);await page.screenshot({path:out+'/offer.png'});await page.getByRole('button',{name:'Start digging',exact:true}).click();await help();const len=await page.evaluate(()=>GameState.fossilDig.sequences[0].length);assert(tier===1?len===3:tier===2?len===4:len>=5&&len<=6);await page.waitForTimeout(len*900+100);assert.equal(await page.evaluate(()=>FossilDig._watching),false);
 for(const [w,h]of [[600,960],[800,1280],[360,640],[960,600]]){await page.setViewportSize({width:w,height:h});await page.screenshot({path:out+`/tier-${tier}-${w}.png`});const r=await page.locator('.dig-actions').boundingBox();assert(r.y>=0&&r.y+r.height<=h+1,JSON.stringify(r));assert.equal(await page.locator('.dig-target').count(),9);}
 await page.setViewportSize({width:600,height:960});const snapshot=await page.evaluate(()=>JSON.stringify(GameState.fossilDig));await page.reload();await page.evaluate(()=>{GameState=SaveManager.load();MiniGameSession.seen.add('fossil-active');SaveManager.resume();});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>JSON.stringify(GameState.fossilDig)),snapshot);
 await page.evaluate(()=>FossilDig.hit((GameState.fossilDig.sequences[0][0]+1)%9));assert.equal(await page.evaluate(()=>GameState.fossilDig.step),0);assert.equal(await page.evaluate(()=>GameState.fossilDig.mistakes),1);
 for(let layer=0;layer<2;layer++){
  const seq=await page.evaluate(()=>GameState.fossilDig.sequences[GameState.fossilDig.layer]);for(const pos of seq){await page.locator(`[data-pos="${pos}"]`).click();await page.waitForTimeout(430);}
  assert.equal(await page.evaluate(()=>GameState.fossilDig.phase),'layer-done');await page.locator('.dig-actions button').click();if(layer===0)await page.waitForTimeout(seq.length*900+100);
 }
 const amount=await page.evaluate(()=>GameState.treasures.crystal);await page.evaluate(()=>FossilDig.reveal());assert.equal(await page.evaluate(()=>GameState.treasures.crystal),amount);await page.screenshot({path:out+'/reward.png'});await page.reload();await page.evaluate(()=>{GameState=SaveManager.load();MiniGameSession.seen.add('fossil-active');SaveManager.resume();});await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>GameState.treasures.crystal),amount);const nodes=await page.evaluate(()=>GameState.completedNodes.length);await page.locator('.dig-actions button').click();assert.equal(await page.evaluate(()=>GameState.completedNodes.length),nodes);assert.equal(await page.evaluate(()=>!!GameState.fossilDig),false);
}
// Atomic shop selling survives a node checkpoint and duplicate clicks.
await page.evaluate(()=>{GameState.treasures={mineral:2,crystal:1,nugget:1};SaveManager.beginNode(GameState.map[0]);ShopEngine.start(GameState.map[0]);});await page.waitForTimeout(400);await page.getByRole('button',{name:'Sell treasures',exact:true}).click();await page.screenshot({path:out+'/shop.png'});const gold=await page.evaluate(()=>GameState.gold);await page.evaluate(()=>{const b=document.querySelector('.dig-sale button');b.click();b.click();});assert.equal(await page.evaluate(()=>GameState.gold),gold+24);assert.equal(await page.evaluate(()=>SaveManager.load().treasures.mineral),0);assert.equal(await page.evaluate(()=>SaveManager.load().gold),gold+24);
// A forced fossil bypasses lure/repel and a throw commits inventory/outcome together.
await init(2,'pokemon');await page.evaluate(()=>{const s=GameState.fossilDig;s.layer=1;s.phase='layer-done';s.pokemonId=138;FossilDig.reveal();GameState.items=[{id:'master_ball',count:2},{id:'repel',count:1},{id:'lure',count:1}];});await page.locator('.dig-actions button').click();await page.waitForTimeout(4500);assert.equal(await page.evaluate(()=>CatchEngine.current.id),138);assert.equal(await page.evaluate(()=>GameState.items.find(i=>i.id==='repel').count),1);await page.locator('.ball-select-btn[data-ball="masterball"]').click();await page.evaluate(()=>{CatchEngine.throwBall();});assert.equal(await page.evaluate(()=>GameState.items.find(i=>i.id==='master_ball').count),1);const size=await page.evaluate(()=>GameState.party.length);await page.reload();await page.evaluate(()=>{GameState=SaveManager.load();MiniGameSession.seen.add('fossil-active');SaveManager.resume();});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>GameState.party.length),size);assert.equal(await page.evaluate(()=>GameState.fossilDig.phase),'catch-result');assert.equal(await page.evaluate(()=>GameState.items.find(i=>i.id==='master_ball').count),1);await page.locator('.dig-actions button').click();
// Full party keeps a saved pending catch; decline or replacement are explicit.
await init(2,'pokemon');await page.evaluate(()=>{GameState.fossilDig.pokemonId=140;while(GameState.party.length<6)GameState.party.push(makePokemon(25,5,'assets/sprites/25.png','Pikachu','electric'));FossilDig.captureOutcome(true,OFFLINE_POKEMON[140]);FossilDig.show();});await help();await page.waitForTimeout(450);assert.equal(await page.locator('.dig-release button').count(),6);await page.screenshot({path:out+'/full-party.png'});await page.locator('.dig-release button').first().click();await page.locator('#modal-ok').click();assert.equal(await page.evaluate(()=>GameState.party.length),6);assert.equal(await page.evaluate(()=>GameState.fossilDig.capture.added),true);await page.locator('.dig-actions button').click();
await init(2,'pokemon');await page.evaluate(()=>{FossilDig.captureOutcome(false,OFFLINE_POKEMON[142]);FossilDig.show();});await page.waitForTimeout(400);assert.match(await page.locator('#dig-dialogue').textContent(),/slipped away/);await page.locator('.dig-actions button').click();
assert.deepEqual(errors,[]);await browser.close();console.log('Fossil scheduling, all-tier sequences, layouts, saved hits/rewards, shop persistence, catch reload/inventory and full party passed.');})().catch(e=>{console.error(e);process.exit(1)});
