const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=process.env.UI_SCREENSHOTS||'/tmp/poketrials-minigames';fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu']});
 const page=await browser.newPage({viewport:{width:960,height:600},hasTouch:true});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message);});await page.route(/^https?:/,r=>r.abort());await page.goto(require('node:url').pathToFileURL(path.join(__dirname,'../index.html')).href);
 await page.evaluate(async()=>{AssetPreloader.ready=true;await Game.startNew(true);GameState.trainerName='Mini';GameState.difficultyTier=2;await Game.confirmStarter(STARTERS[0]);window.realTier=getSkillTier;getSkillTier=()=>GameState.difficultyTier;});await page.waitForTimeout(700);
 const help=async()=>{if(await page.locator('.minigame-guide').count())await page.locator('.minigame-guide button').click();};
 const start=async(name,tier=2)=>{await page.evaluate(async({name,tier})=>{GameState.difficultyTier=tier;const e=eval(name);await e.start({idx:0,type:'test'});if(e.startGame)e.startGame();},{name,tier});await page.waitForTimeout(450);await help();};
 const shot=async name=>{await page.waitForTimeout(500);await page.evaluate(()=>{const s=document.querySelector('.screen.active');if(s)s.scrollTop=0;});await page.screenshot({path:out+'/'+name+'.png'});assert.deepEqual(errors,[],name);};

 await start('MortyEngine',2);await page.waitForFunction(()=>!MortyEngine._locked);await page.evaluate(()=>MortyEngine._sequence.forEach(i=>document.querySelectorAll('.morty-procession button')[i].click()));assert.equal(await page.evaluate(()=>MortyEngine._hits),1);await page.locator('.minigame-next').click();assert.equal(await page.evaluate(()=>MortyEngine._round),1);
 await start('JasmineEngine',2);await page.waitForFunction(()=>!JasmineEngine._locked);await page.evaluate(()=>JasmineEngine._btns[(JasmineEngine._seq[0]+1)%4].click());assert.equal(await page.evaluate(()=>JasmineEngine._mistakes),1);await page.getByRole('button',{name:'Repair and replay'}).click();await page.waitForFunction(()=>!JasmineEngine._locked);await page.evaluate(()=>JasmineEngine._seq.forEach(i=>JasmineEngine._btns[i].click()));await page.locator('.minigame-next').click();assert.equal(await page.evaluate(()=>JasmineEngine._round),1);await shot('jasmine-repaired');
 await start('WobbuffetEngine',2);await page.getByRole('button',{name:'Ready — incoming attack'}).click();await page.evaluate(()=>{const a=WobbuffetEngine._sequence[0];[...document.querySelectorAll('.wobbu-choice-btn')].find(b=>b.textContent.trim()===a.counter).click();});assert.equal(await page.evaluate(()=>WobbuffetEngine._hits),1);await page.locator('.minigame-next').click();assert.equal(await page.evaluate(()=>WobbuffetEngine._round),1);
 await start('SabrinaEngine',2);await page.waitForSelector('.sabrina-tray-piece');await page.locator('.sabrina-tray-piece').first().click();await page.evaluate(()=>{const p=SabrinaEngine._trayPieces[SabrinaEngine._selectedTray];const slot=[...document.querySelectorAll('.sabrina-slot-empty')].find(e=>Number(e.dataset.row)===p.row&&Number(e.dataset.col)===p.col);slot.click();});assert.equal(await page.locator('.sabrina-piece-placed').count(),1);assert.equal(await page.locator('.sabrina-piece-placed').textContent(),'');await page.getByRole('button',{name:'Show reference',exact:true}).click();assert.equal(await page.locator('.sabrina-reference').isVisible(),true);await shot('sabrina-grid');
 await start('ErikaEngine',3);await shot('erika-fixed');await start('WhitneyEngine');await shot('whitney-fixed');await start('ChuckEngine',3);await shot('chuck-fixed');
 await page.evaluate(()=>{MiniGameSession.next(()=>{});MiniGameSession.stop();});assert.equal(await page.locator('.minigame-next').count(),0);
 assert.deepEqual(errors,[]);await browser.close();console.log('Minigame flow checks passed: ghost sequence, forge retry, counter readiness, puzzle placement, session cleanup.');
})().catch(e=>{console.error(e);process.exit(1)});
