const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const output=process.env.UI_SCREENSHOTS||fs.mkdtempSync('/tmp/poketrials-ui-');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--disable-gpu']});
 const page=await browser.newPage({viewport:{width:960,height:600},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());await page.goto(require('node:url').pathToFileURL(path.join(__dirname,'../index.html')).href);
 await page.evaluate(async()=>{await Game.startNew(true);GameState.trainerName='Pixel';GameState.trainerAge=10;GameState.difficultyTier=2;await Game.confirmStarter(STARTERS[0]);});await page.waitForTimeout(650);await page.screenshot({path:output+'/map.png'});
 await page.evaluate(()=>{const p=makePokemon(2,31,OFFLINE_POKEMON[2].sprites.front_default,'Ivysaur','grass');p.backSpriteUrl=OFFLINE_POKEMON[2].sprites.back_default;GameState.party[0]=p;GameState.deck=p.deck;const opp=makePokemon(18,28,OFFLINE_POKEMON[18].sprites.front_default,'Pidgeot','flying');opp.hp=1000;opp.maxHp=1000;setBattleBg('flying',false);showScreen('battle');BattleEngine._initBattle(p,opp,false);BattleEngine.state.hand=[...p.deck.slice(0,3),p.deck[3],p.deck.at(-1)];BattleEngine._render();});await page.waitForTimeout(650);
 for(const [w,h] of [[960,540],[960,600],[600,960],[1280,800],[800,1280],[1024,1180]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(150);await page.screenshot({path:`${output}/battle-${w}-${h}.png`});const r=await page.evaluate(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom}};return{log:rect('#battle-log'),player:rect('#screen-battle .battle-sprite-wrap.player'),opponent:rect('#screen-battle .battle-sprite-wrap.opponent'),hud:rect('#player-hud'),background:rect('#screen-battle .battle-bg-img'),card:rect('#hand-area .card'),intent:rect('#screen-battle .enemy-intent'),exit:rect('#screen-battle .battle-save-exit')}});assert.ok(Math.abs(r.player.bottom-r.background.h*.72)<2,'Player feet on platform');assert.ok(Math.abs(r.opponent.bottom-r.background.h*.475)<2,'Opponent feet on platform');assert.ok(r.player.w>r.opponent.w*1.3,'Foreground larger');assert.ok(r.hud.bottom<r.log.y,'HUD clears log');assert.ok(r.card.bottom<=h-3,'Card fits');assert.ok(r.intent.x>=r.exit.right,'Intent clears exit');}
 await page.setViewportSize({width:960,height:600});const expected=await page.evaluate(()=>BattleEngine.state.hand.filter(c=>c.source).length);assert.equal(await page.locator('#hand-area .card-flip-trigger').count(),expected);const energy=await page.evaluate(()=>BattleEngine.state.energy);await page.locator('#hand-area .card-flip-trigger').first().click();await page.waitForTimeout(400);assert.equal(await page.locator('.card-flip-dialog').count(),1);assert.equal(await page.locator('#screen-battle .inspect-card').count(),0);await page.screenshot({path:output+'/flip-offline.png'});await page.locator('.card-flip-stage').click();await page.waitForTimeout(380);assert.equal(await page.locator('.card-flip-dialog').count(),0);assert.equal(await page.evaluate(()=>BattleEngine.state.energy),energy);
 // Substitute only image transport to verify successful loading, without relying on card hosts.
 await page.evaluate(()=>{const c=BattleEngine.state.hand.find(c=>c.source);c.source={...c.source,localImage:'assets/sprites/2.png'};BattleEngine._render();});await page.locator('#hand-area .card-flip-trigger').first().click();await page.waitForTimeout(400);assert.equal(await page.locator('.flip-back img').isVisible(),true);assert.equal(await page.locator('.flip-unavailable').isVisible(),false);await page.keyboard.press('Escape');await page.waitForTimeout(380);
 await page.evaluate(()=>{window.fishingResults=[];FishingTiming.start(2,b=>window.fishingResults.push(b));});await page.waitForTimeout(600);
 for(let i=0;i<3;i++){await page.locator('#angling-hook-btn').click();await page.evaluate(()=>{FishingTiming.session.angle=FishingTiming.session.target;FishingTiming.tap();});}
 assert.equal(await page.locator('#angling-hook-btn').textContent(),'REVEAL CATCH');await page.locator('#angling-hook-btn').click();assert.deepEqual(await page.evaluate(()=>window.fishingResults),[1]);assert.equal(await page.evaluate(()=>FishingTiming.session),null);assert.deepEqual(await page.evaluate(()=>[FishingTiming.score(359,1,30),FishingTiming.score(25,1,30),FishingTiming.score(180,1,30)]),[2,1,0]);
 for(const [w,h] of [[960,540],[960,600],[600,960],[1280,800],[800,1280]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>FishingTiming.start(3,()=>{}));await page.waitForTimeout(200);await page.locator('#angling-hook-btn').click();await page.waitForTimeout(400);await page.screenshot({path:`${output}/fishing-${w}-${h}.png`});const b=await page.locator('#angling-hook-btn').boundingBox();assert.ok(b.y>=0&&b.y+b.height<=h,'Reel fits');}
 await page.evaluate(()=>showScreen('map'));await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>FishingTiming.session),null,'Leaving stops animation');
 // Clue and choice layout uses local sprites, even with the network blocked.
 for(const [w,h] of [[960,540],[600,960]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>{FishingEngine._puzzle=_buildMistyPuzzle(2,[],1);FishingEngine._clueIdx=FishingEngine._puzzle.clues.length;FishingEngine._answered=false;FishingEngine._showClueStage();});await page.waitForTimeout(600);assert.equal(await page.locator('.fishing-card-img').count(),4);await page.screenshot({path:`${output}/fishing-choices-${w}.png`});}
 await page.locator('.fishing-choice-card').first().click();await page.waitForTimeout(200);assert.equal(await page.locator('#challenge-continue-btn').isVisible(),true);
 await page.setViewportSize({width:960,height:540});await page.evaluate(async()=>{FishingTiming.stop();const node=GameState.map.find(n=>n.type==='boss');await BossEngine.start(node);BossEngine.startBattle();});await page.waitForTimeout(650);await page.screenshot({path:output+'/boss-compact.png'});const g=await page.evaluate(()=>{const r=s=>document.querySelector(s).getBoundingClientRect();return{hud:r('#boss-battle-area .hud-player').bottom,log:r('#boss-battle-log').top,pips:r('#boss-party-bar').top,intent:r('#boss-battle-area .enemy-intent').bottom}});assert.ok(g.hud<g.log);assert.ok(g.pips>=g.intent);
 // Reduced motion disables decorative bobbing and still supports a playable timing ring.
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>FishingTiming.start(2,()=>{}));assert.ok(await page.evaluate(()=>FishingTiming.session.speed<88));
 assert.deepEqual(errors,[]);console.log('Tablet UI checks passed; screenshots: '+output);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
